### ISSUE TITLE
Official website not working

### ISSUE THREAD

**Issue by imilo** [MyCollab/mycollab#25] opened 2017-01-29 15:38 UTC
Hello! At this moment almost all links to your website are not working. Both for Pro and Community editions, link for download, link for documentation, etc. Everywhere I get Nginx error **404 Not Found**

Please fix your website.

Also for such problems - add a tutorial how to install community version (self-hosted) here on GitHub. Otherwise there is no way to install correctly your project

**Comment by haiphucnguyen** [comment] 2017-01-30 19:16
Thank you. We have the problem with our hosting and the issue is fixed now.

Hai

**Closed by haiphucnguyen** 2017-01-30 19:16 UTC
